# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '代码相似度量研究.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1877, 965)
        MainWindow.setStyleSheet("QMainWindow{background:grey;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 93, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 440, 93, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(660, 860, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(790, 870, 72, 15))
        self.label_3.setObjectName("label_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(130, 20, 441, 371))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(880, 870, 151, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(130, 440, 441, 341))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(740, 20, 371, 371))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(740, 440, 371, 341))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_pic1 = QtWidgets.QLabel(self.centralwidget)
        self.label_pic1.setGeometry(QtCore.QRect(1250, 20, 231, 761))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_pic1.setFont(font)
        self.label_pic1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pic1.setStyleSheet("border-image: url(:/newPrefix/images_test/scan.gif);")
        self.label_pic1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic1.setObjectName("label_pic1")
        self.label_pic2 = QtWidgets.QLabel(self.centralwidget)
        self.label_pic2.setGeometry(QtCore.QRect(1620, 20, 231, 761))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_pic2.setFont(font)
        self.label_pic2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pic2.setStyleSheet("border-image: url(:/newPrefix/images_test/scan.gif);")
        self.label_pic2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic2.setObjectName("label_pic2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1150, 20, 93, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1520, 20, 93, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(640, 20, 93, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(640, 440, 93, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1877, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "上传源文件1"))
        self.pushButton_2.setText(_translate("MainWindow", "上传源文件2"))
        self.pushButton_3.setText(_translate("MainWindow", "开始检测"))
        self.label_3.setText(_translate("MainWindow", "检测结果："))
        self.label_pic1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_pic2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "显示有向图1"))
        self.pushButton_5.setText(_translate("MainWindow", "显示有向图2"))
        self.pushButton_6.setText(_translate("MainWindow", "CFG1显示"))
        self.pushButton_7.setText(_translate("MainWindow", "CFG2显示"))

import sys
from PyQt5.QtWidgets import QMainWindow, QApplication, QFileDialog
from PyQt5 import QtWidgets,QtCore,QtGui
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

from 代码相似度量研究 import Ui_MainWindow
from run_file import run_cfg, vector_similarity, weighted_average
from run_file import run_jpg


import numpy as np
from ge import DeepWalk
import networkx as nx
from numpy.linalg import norm

class DetailUI(Ui_MainWindow,QMainWindow):
    def __init__(self):
        super(DetailUI, self).__init__()
        self.setupUi(self)
        self.setWindowTitle('代码相似度检测')
        self.pushButton.clicked.connect(self.click)
        self.pushButton_2.clicked.connect(self.click2)
        self.pushButton_3.clicked.connect(self.examine)
        self.pushButton_3.clicked.connect(self.openexamine)
        self.pushButton_4.clicked.connect(self.openimage)
        self.pushButton_5.clicked.connect(self.openimage1)
        self.pushButton_6.clicked.connect(self.CFGshow)
        self.pushButton_7.clicked.connect(self.CFGshow1)
        #界面美化
        self.label_pic1.setStyleSheet("QLabel{background:white;}")
        self.label_pic2.setStyleSheet("QLabel{background:white;}")
        self.pushButton.setStyleSheet(''' 
                             QPushButton
                             {text-align : center;
                             background-color : white;
                             font: bold;
                             border-color: gray;
                             border-width: 2px;
                             border-radius: 10px;
                             padding: 6px;
                             height : 14px;
                             border-style: outset;
                             font : 14px;}
                             QPushButton:pressed
                             {text-align : center;
                             background-color : light gray;
                             font: bold;
                             border-color: gray;
                             border-width: 2px;
                             border-radius: 10px;
                             padding: 6px;
                             height : 14px;
                             border-style: outset;
                             font : 14px;}
                             ''')
        self.pushButton_2.setStyleSheet(''' 
                                     QPushButton
                                     {text-align : center;
                                     background-color : white;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     QPushButton:pressed
                                     {text-align : center;
                                     background-color : light gray;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     ''')
        self.pushButton_3.setStyleSheet(''' 
                                     QPushButton
                                     {text-align : center;
                                     background-color : white;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     QPushButton:pressed
                                     {text-align : center;
                                     background-color : light gray;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     ''')
        self.pushButton_4.setStyleSheet(''' 
                                     QPushButton
                                     {text-align : center;
                                     background-color : white;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     QPushButton:pressed
                                     {text-align : center;
                                     background-color : light gray;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     ''')
        self.pushButton_5.setStyleSheet(''' 
                                     QPushButton
                                     {text-align : center;
                                     background-color : white;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     QPushButton:pressed
                                     {text-align : center;
                                     background-color : light gray;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     ''')
        self.pushButton_6.setStyleSheet(''' 
                                     QPushButton
                                     {text-align : center;
                                     background-color : white;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     QPushButton:pressed
                                     {text-align : center;
                                     background-color : light gray;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     ''')
        self.pushButton_7.setStyleSheet(''' 
                                     QPushButton
                                     {text-align : center;
                                     background-color : white;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     QPushButton:pressed
                                     {text-align : center;
                                     background-color : light gray;
                                     font: bold;
                                     border-color: gray;
                                     border-width: 2px;
                                     border-radius: 10px;
                                     padding: 6px;
                                     height : 14px;
                                     border-style: outset;
                                     font : 14px;}
                                     ''')

    def click(self):
        # 选择cpp源文件1并以文本的形式输出到多行文本框textEdit
        global path
        self.filename = QFileDialog.getOpenFileName()
        path = self.filename[0]
        run_cfg(path)
        run_jpg(path)
        with open(path, 'r') as f:
            self.textEdit.setPlainText(f.read())

    def click2(self):
        # 选择cpp源文件2并以文本的形式输出到多行文本框textEdit_5
        global path1
        self.filename = QFileDialog.getOpenFileName()
        path1 = self.filename[0]
        run_cfg(path1)
        run_jpg(path1)
        with open(path1, 'r') as f:
            self.textEdit_5.setPlainText(f.read())
        return self.filename[0]

    def CFGshow(self):
        # 显示源文件1的GFC文件
        global path
        with open(path.split('.')[0]+'.cfg', 'r') as f:
            self.textEdit_2.setPlainText(f.read())

    def CFGshow1(self):
        # 显示源文件2的GFC文件
        global path1
        with open(path1.split('.')[0]+'.cfg', 'r') as f:
            self.textEdit_4.setPlainText(f.read())

    def openimage(self):
        #显示源文件1的有向图
        imgName, imgType = QFileDialog.getOpenFileName(self, "打开图片", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QtGui.QPixmap(imgName).scaled(self.label_pic1.width(), self.label_pic1.height())
        self.label_pic1.setPixmap(jpg)

    def openimage1(self):
        # 显示源文件2的有向图
        imgName, imgType = QFileDialog.getOpenFileName(self, "打开图片", "", "*.jpg;;*.png;;All Files(*)")
        jpg = QtGui.QPixmap(imgName).scaled(self.label_pic1.width(), self.label_pic1.height())
        self.label_pic2.setPixmap(jpg)

    def examine(self)  :
        global path
        global path1
        # 输出相似度检测的结果
        G = nx.read_gml(path.split('.')[0]+'.gml')
        model = (DeepWalk(G, walk_length=10, num_walks=80, workers=1)).train(embed_size=64, window_size=5, iter=3)
        # model_ = model.train(embed_size=64,window_size=5, iter=3)
        v1 = weighted_average(G, model)

        G1 = nx.read_gml(path1.split('.')[0]+'.gml')
        model1 = (DeepWalk(G1, walk_length=10, num_walks=80, workers=1)).train(embed_size=64, window_size=5, iter=3)
        # model1_ = model1.train(embed_size=64,window_size=5, iter=3)
        v2 = weighted_average(G1, model1)

        # print(vector_similarity(v1, v2))
        result = np.float(vector_similarity(v1, v2))
        file_handle = open('E:/结果.txt', mode='w')
        file_handle.write('相似度：{:.2%}'.format(result))
        #将相似度结果保存在结果.txt文档并显示

    def openexamine(self):
        with open('E:/结果.txt', 'r') as f:
            self.textEdit_3.setPlainText(f.read())

    def runModel(self):
        pass

if __name__ == "__main__":
    app = QApplication(sys.argv)
    main = DetailUI()
    main.show()
    sys.exit(app.exec_())

